# Generated by Django 6.0.2 on 2026-09-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meniitem',
            name='Description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
