# Generated by Django 6.0.2 on 2026-09-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_user_profile_image_user_role'),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allergies',
            field=models.ManyToManyField(blank=True, limit_choices_to={'is_allergen': True}, related_name='allergic_users', to='app.ingredient'),
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_preferences',
            field=models.TextField(blank=True, default=''),
        ),
    ]
